# Conda environment for ichorCNA and visualization (R-based)
channels:
  - conda-forge
  - bioconda

dependencies:
  - r-base>=4.4
  - bioconductor-hmmcopy
  - hmmcopy
  - bioconductor-genomicranges
  - bioconductor-genomeinfodb
  - r-optparse
  - r-plyr
  - samtools
  - r-tidyverse
  - r-data.table
  - r-ggplot2
  - r-pheatmap
