container:
  cfdna_wgs: "~/sing_containers/cfdna_wgs.1.0.0.sif"
  default: "~/sing_containers/biotools.1.0.2.sif"

dir:
  cfdna_wgs_repo: "./"
  cfdna_wgs_scripts: "workflow/scripts"
  data: "test"

threads:
    default: "4"