container: "~/sing_containers/mpnst.sif"
log_dir: "test/logs"
threads: "4"
inputs_dir: "test/inputs"
frag_bam_dir: "test/frag-bam"
wig_dir: "test/wig"
ichor_hg19_dir: "test/ichor_hg19"
ichor_hg38_dir: "test/ichor_hg38"
cna_bam_dir: "test/bam"